[package]
name = "CVE-2023-38831"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6"

[[bin]]
name = "winrar-script-exploiter"
path = "src/main.rs"
